### ISSUE TITLE
Telemetry added in PR #91 is unable to be disabled

### ISSUE THREAD

**Issue by CodyPubNub** [DataDog/datadog-go#114]
Hello,

This new code landed in [v3.0.0](https://github.com/DataDog/datadog-go/compare/v2.3.0...v3.0.0)

Telemetry was first introduced in this PR: https://github.com/DataDog/datadog-go/pull/91

This is the specific commit on the PR where the telemetry initially landed: https://github.com/DataDog/datadog-go/pull/91/commits/b4f4ba0cba37f1ed3ba960a598e443452b644712

These lines were ultimately added in master: https://github.com/DataDog/datadog-go/blob/b6a27b8550f3d406c2cd02617122141cd816dc46/statsd/statsd.go#L256-L275

There is no mention in the PR description of the concept of telemetry being added. Furthermore, there are no documentations or configs mentioning telemetry.

I found these metrics being emitted during a read through of a TCP dump of the statsd traffic on our application:

```
sudo tcpdump -i any -n udp dst port 8125 -lev -s 0 -A
datadog.dogstatsd.client.packets_sent:1|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_sent:575|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped:1|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped:521|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_queue:0|c|#client:go,transport:udp
datadog.dogstatsd.client.packets_dropped_writer:1|c|#client:go,transport:udp
datadog.dogstatsd.client.bytes_dropped_writer:521|c|#client:go,transport:udp
```

There should to be configuration available to turn this telemetry off, but there isn't, as far as I can tell.

Regards,
Cody

**Comment by arbll** [comment]
Hi @CodyPubNub,

Thanks for opening this issue, we indeed forgot to document the list of available metrics injected by this client. I am also adding an option to disable it if needed.

Sorry again for the misunderstanding about billing, those metrics were marked as non-billable since their introduction.

Cheers,
Arthur

**Comment by CodyPubNub** [comment]
Hi Arthur,

I appreciate the swift response to this. Looking forward to PR #117

Thanks,
Cody
