### ISSUE TITLE
Go Modules Support

### ISSUE THREAD

**Issue by spsoto** [DataDog/datadog-go#119]
Currently there are no `go.mod` and `go.sum` files in the repo. `go mod` is currently adding `v<version>-incompatible` tags to `go.mod` files but they are prone to breaking whenever we `go get -u` the dependency in modules mode.

It'd be very helpful to have Go Modules support to make dependency management more deterministic.

**Comment by KevinAnthony** [comment]
Is there any movement on this? this would be useful for a us as well

**Comment by gyant** [comment]
This seriously needs go mod support. Any ETA on this?

**Comment by hush-hush** [comment]
HI @spsoto,

The new major version was delayed more than we expected but it's finally released. We've added go modules support.

See the CHANGELOG for all the breaking changed in the new `v5` version.

I'm closing this issue but feel free to reopen it if needed.
