### ISSUE TITLE
Namespace is ignored

### ISSUE THREAD

**Issue by vmogilev** [DataDog/datadog-go#13]
Please check why Namespace is being ignored on SimpleEvent() calls

**Comment by diasjorge** [comment]
The same happens now when sending a service check. As it happens with Events, they call directly sendMsg instead of using send function (which calls format before sendMsg)

**Comment by diasjorge** [comment]
is this a bug or feature?

**Comment by arbll** [comment]
This is intended. For events I am not sure how it would make sense to have `my_prefix.This is my event title`. As for Service checks it's not as clear-cut but this is something consistent across all our clients.
