### ISSUE TITLE
please tag and version this project

### ISSUE THREAD

**Issue by aviau** [DataDog/datadog-go#14]
Hello,

Can you please tag and version this project?

I am the Debian Maintainer for datadog-go and versioning would help Debian keep up with development.

**Comment by truthbk** [comment]
@aviau we should definitely begin doing so. I will keep you posted, thanks, for bringing this up.

**Comment by aviau** [comment]
Thanks! Please close this issue when you make the first tag so that I can notified :)

**Comment by truthbk** [comment]
@aviau released `1.0.0`. We will follow versioning/tagging guidelines from now on. Thanks @aviau.
