### ISSUE TITLE
ddtrace.Logger

### ISSUE THREAD

**Issue by fantyz** [DataDog/datadog-go#160]
Hi,

How do I easily make a `ddtrace.Logger` for use with the `tracer.WithLogger` option? I can't seem to find anything to help me create one from even a standard log. Do I really need to create my own custom wrapper?

It seems like a strange design decision to make that interface into something that the standard log in go doesn't implement out of the box?

**Comment by hush-hush** [comment]
Hi @fantyz,

This is the Dogstatsd client repo for Go. Please open an issue on the [trace repo](https://github.com/DataDog/dd-trace-go) so the right team can answer the question.

Thanks
