### ISSUE TITLE
Optimal UDP payload size for localhost

### ISSUE THREAD

**Issue by CAFxX** [DataDog/datadog-go#168]
Currently the ["optimal" payload size is set to 1432 for UDP](https://github.com/DataDog/datadog-go/blob/3255e6186e83fad1e447573c9fa03dd13c023394/statsd/statsd.go#L35-L41) even if both statsd client and agent are running on the same host.

Using an MTU of slightly less than 1500 is a pretty conservative approach, appropriate at best for sending UDP datagrams over the internet or heterogeneous networks. The argument that fragmented UDP packets are completely lost if any one of their fragments is lost, while technically correct, is already unlikely to be a real factor in properly run datacenter networks and, even more so, when the communication happens purely over localhost.

On my mac, the localhost MTU defaults to 16K. On linux it also [used to default to 16K, but has been 64K for quite a few years](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=0cf833aefaa85bbfce3ff70485e5534e09254773). In Windows the loopback MTU seems to be basically unlimited. On the BSDs I can only offer anecdotal evidence that the loopback MTU defaults to 16K (in line with that of macs).

I think it would be safe to raise the UDP MTU to slightly less than 16K if the agent address [resolves to a loopback address](https://golang.org/pkg/net/#IP.IsLoopback), or even better to whatever number is returned by [`net.Interface.MTU`](https://golang.org/pkg/net/#Interface) for the loopback interface. This would bring benefits as it would cut down by an order of magnitude the number of syscalls made by the client (and by the agent).

In a nutshell, the proposed change would be adding [here](https://github.com/DataDog/datadog-go/blob/3255e6186e83fad1e447573c9fa03dd13c023394/statsd/statsd.go#L297-L299) something along the lines of:

```golang
	if o.MaxBytesPerPayload == 0 {
		if isLoopback(c.addrOption) {
			o.MaxBytesPerPayload = OptimalLoopbackUDPPayloadSize // e.g. slightly less than 16K
		} else {   
			o.MaxBytesPerPayload = OptimalUDPPayloadSize
		}
	}
```

where `isLoopback` would parse/resolve the address and use [`net.IP.IsLoopback`](https://golang.org/pkg/net/#IP.IsLoopback) to check if the agent is running on loopback. This won't unfortunately cover the rather common case of client and agent being on the same host, but not talking via loopback (e.g. different pods on the same host in kubernetes) but it's a start (we could also further extend this to check if the IP of the agent matches one of the IPs of the interfaces of the host the client is running on, but this is a bit more sketchy so maybe it should be done later).

We would probably also need to change the [buffer size](https://github.com/DataDog/datadog-agent/blob/c231693b77b97ebb1ff2b9c3beb1d18986be6fd7/docs/dogstatsd/configuration.md#dogstatsd_buffer_size) of dogstatsd from 8K to 16K (even better, should be raised to 64K since [`MaxUDPPayloadSize` is ~64K](https://github.com/DataDog/datadog-go/blob/3255e6186e83fad1e447573c9fa03dd13c023394/statsd/statsd.go#L43-L49)) and lowering `dogstatsd_queue_size` as needed to maintain the same memory usage. If this is not possible right away, it should be still feasible to raise the client's loopback optimal UDP payload size to slightly less than 8K. Note also that there seem to be no reason to not [simply hardcode a 64K buffer for receiving UDP messages](https://github.com/DataDog/datadog-agent/blob/ccbbaa5e62b966a7cb5bc356f5ce6ac3e06d32c1/pkg/dogstatsd/listeners/udp.go#L81) in dogstatsd, since we use [only a single buffer](https://github.com/DataDog/datadog-agent/blob/ccbbaa5e62b966a7cb5bc356f5ce6ac3e06d32c1/pkg/dogstatsd/listeners/udp.go#L98-L119): I opened a draft PR for that [here](https://github.com/DataDog/datadog-agent/pull/6470).

**Comment by remeh** [comment]
Hey @CAFxX,
Thanks for the very interesting point-of-view and detailed issue. I will give a look into it and we also have benchmarks / scenarios here I'm interested to run this against.
You've addressed it but I'll carefully validate that it won't just trade RAM usage against throughput, which is something which is an issue in a lot of real-world scenarios. (but you're right that tweaking the `dogstatsd_queue_size` could do the job).
In all honesty, maybe not in detail this week but I'll look into this soon, it's very interesting.

**Comment by hush-hush** [comment]
Closing following this comment https://github.com/DataDog/datadog-agent/pull/6470#issuecomment-763763740

Also all those values are configurable if needed.

Feel free to reopen if needed.
