### ISSUE TITLE
Please improve the experience when configuring an app with env vars

### ISSUE THREAD

**Issue by michaelgoodrx** [DataDog/datadog-go#177]
12 factor apps use environment variables for configuration. This is also the approach you recommend for setting up Datadog in Kubernetes.

Even when we aren't using the Datadog Agent (eg. in dev environments and in local development), we would like to leave all the metrics sending code mostly unchanged. Since we aren't running the agent, `DD_AGENT_HOST` is left empty or unset. When we run `statsd.New` and pass in an empty string so the statsd client gets config from environment variables, if no environment variables are set, we get an error.

When `statsd.New` can't start because it can't find any environment variables like `DD_AGENT_HOST`, we'd like to just switch to the `NoOpClient` so all the code is unchanged and the app can still run. But you don't provide a way to detect this case, so we have to pre-emptively check the same environment variables you check, which breaks the abstraction.

A few ways to fix this:

 - default to `127.0.0.1:8125` if the address isn't set in any other way - that way we don't have to make any changes, and for many people it would "just work"

 - export an error representing cases where no address is set - that way we could check for this case explicitly

**Comment by hush-hush** [comment]
Hi @michaelgoodrx,

Could you please tell me which version of the client you are using ? If you call `statsd.New("")` without setting 
`DD_AGENT_HOST` an error is currently returned `No address passed and autodetection from environment failed`.

Thanks

**Comment by hush-hush** [comment]
I'm going to close this, feel free to reopen if needed

**Comment by tangphillip** [comment]
I am also experiencing this. Please disable the datadog agent instead of panicking when no datadog address is set.

We're running
github.com/DataDog/datadog-go v3.6.0
gopkg.in/DataDog/dd-trace-go.v1 v1.25.0

**Comment by tangphillip** [comment]
@hush-hush please reopen
