### ISSUE TITLE
Profiler doesn't stop cleanly if uploads are failing

### ISSUE THREAD

**Issue by maebeam** [DataDog/datadog-go#196]
Calling `profiler.Stop()` if the profiler is unable to submit profiles hangs the shutdown process

**Comment by hush-hush** [comment]
Hi @maebeam,

I think you have the wrong repo. This one is dedicated to [DogStatsD](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent). You might want to reopen you issue here https://github.com/DataDog/dd-trace-go.

I'm closing this issue, but feel free to reopen it if needed.

Thanks.
