### ISSUE TITLE
Buffered client is inefficient

### ISSUE THREAD

**Issue by ejholmes** [DataDog/datadog-go#20]
I'm investigating some packet drops in dogstatsd, which are caused by a producer that generates a lot of packets, and uses `statsd.NewBuffered`.

Because this system generates a lot of statsd packets, we (naively) assumed that a buffered statsd client would take load off of dogstatsd. However, we noticed that packets would get dropped frequently, and would follow a step function:

![](http://i.imgur.com/uj4miGd.png)

When buffering is enabled, the statsd client will periodically flush its entire internal buffer every 100 milliseconds, which can easily overload dogstatsd, forcing the kernel to drop packets. I think the primary advantage of buffering is to build up a packet so that it's as close to `OptimalPayloadSize` as it can be, but once we have a packet big enough to flush, it should be flushed so that there's a smoother distribution of packet sends.

**Comment by ethanwp** [comment]
Naive question: what is the advantage of delivering stats over UDP vs TCP? Is the data rate particularly high and particularly time sensitive (say must be delivered with 100 milliseconds). Feel free to educate me over slack. thanks!

**Comment by ejholmes** [comment]
> what is the advantage of delivering stats over UDP vs TCP?

In general, UDP performs better than TCP, since it's fire and forget, and drops are infrequent in a reliable network (e.g. over the loopback). Drops can still happen, like in the above scenario, but in general, it's better to drop than to lock up the application.

> Is the data rate particularly high and particularly time sensitive (say must be delivered with 100 milliseconds)

It's more that individual packets are not critical enough that they require an acknowledgement.

**Comment by aseemk** [comment]
Any official recommendation from the Datadog team here? Thanks!
