### ISSUE TITLE
How do I check for errors sending packets?

### ISSUE THREAD

**Issue by MichaelSnowden** [DataDog/datadog-go#248]
I see that send errors are stored in the sender.metrics field in a SenderMetrics struct, but I don't know how to access it. I was hoping the FlushTelemetryMetrics would provide something, but it doesn't seem to contain errors sending packets.

**Comment by MichaelSnowden** [comment]
Basically, I see t hat they're recorded and sent to the server with this format: https://docs.datadoghq.com/developers/dogstatsd/high_throughput/?code-lang=go#client-side-telemetry

But how do I monitor them from within my Go app?

**Comment by hush-hush** [comment]
Hi @MichaelSnowden,

The `GetTelemetry` method is there for this https://pkg.go.dev/github.com/DataDog/datadog-go/v5/statsd#Client.GetTelemetry.

It will return [this struct](https://pkg.go.dev/github.com/DataDog/datadog-go/v5/statsd#Telemetry), `TotalPayloadsDroppedWriter` or `TotalPayloadsDropped` should be what you are looking for.

**Comment by hush-hush** [comment]
Hi @MichaelSnowden,

I'm going to close this issue. Feel free to reopen it if needed.
