### ISSUE TITLE
http client

### ISSUE THREAD

**Issue by triggity** [DataDog/datadog-go#26]
can we get an client for the http interface  in addition to the statsd client. I'm happy to do it myself, as long as it's something we want

**Comment by ojongerius** [comment]
Is https://github.com/zorkian/go-datadog-api what you are after? Would be a shame to have duplication of effort.

Might be worth considering merging these projects too.

Thoughts?

**Comment by arbll** [comment]
Hey there, 

I'll close this one, feel free to re-open if you have any question. 
Please use https://github.com/zorkian/go-datadog-api to interact with the Datadog http api.
