### ISSUE TITLE
How to authenticate the client?

### ISSUE THREAD

**Issue by vschoener** [DataDog/datadog-go#281]
Hello,

I'm trying to find in this documentation and [there](https://docs.datadoghq.com/fr/developers/) how I can authenticate my client?

I have a use case where I would like to send metrics from a CLI command to our datadogs server. 

Could you light me on that?

**Comment by carlosroman** [comment]
There is no authentication needed when sending data to a DogStatsD server. Your DD API key should be configured on the DogStatsD server (or Datadog Agent) and that handles the authentication with DD.
