### ISSUE TITLE
Please tag 1.1.0 release

### ISSUE THREAD

**Issue by Jasrags** [DataDog/datadog-go#29]
Hello, 

Could you guys please tag a 1.1.0 release? I am using glide and currently i have to bind my dep to a sha to pick up any new code. A 1.1.0 tag would help greatly! Thanks!

**Comment by Jasrags** [comment]
@truthbk

**Comment by Taik** [comment]
Would appreciate this as well.

**Comment by truthbk** [comment]
@Jasrags @Taik by popular demand, 1.1.0 is now out! Sorry for the delay -- horrible response time.
