### ISSUE TITLE
Is it possible to export eventAlertType? (also eventPriority)?

### ISSUE THREAD

**Issue by thomas91310** [DataDog/datadog-go#41]
I would like to have a generic function/method in my code to be able to send events to dogstatsd.
I would like to be able to provide to the callers of this function/method the choice of alerting/priority level they want to use.

Something like this:
```golang 
func (dds DataDogSVC) SendEvent(componentName string, eventName string, eventDescription string, extraTags []string, alertType statsd.EventAlertType) error
```

Unfortunately, I cannot do this because `eventAlertType` is not an exported type. (For reference, @Jasrags mentions this too in this PR: https://github.com/DataDog/datadog-go/pull/19)

Right now, the method I defined looks like:
```golang
func (dds DataDogSVC) SendEvent(componentName string, eventName string, eventDescription string, extraTags []string, alertType string) error {
	eventAlertType := statsd.Info
	if alertType == "warning" {
		eventAlertType = statsd.Warning
	} else if alertType == "error" {
		eventAlertType = statsd.Error
	} else if alertType == "success" {
		eventAlertType = statsd.Success
	}
	//create the event and send it to dogstatsd

	return nil
}
```
I don't think it would be a tremendous change to export `eventAlertType` and `eventPriority` and would be a little bit nicer to use in my opinion.

**Comment by masci** [comment]
Hi @thomas91310 thanks for reporting. 
I think this is a good idea, do you want to open a PR with the fix? 😊

**Comment by thomas91310** [comment]
yes, sure!

**Comment by arbll** [comment]
Closing this one, feel free to re-open if you still need this.
