### ISSUE TITLE
Confusing tagging in README 

### ISSUE THREAD

**Issue by weichuliu** [DataDog/datadog-go#50]
In the example code the tag is added like `c.Tags = append(c.Tags, "us-east-1a")` however if I understand correctly, this should be a pair.

I've checked the example in python library, and found the tag is `:` splitted string, making it a key and a value.

Is go-version library having special way setting tags or is it a typo?

**Comment by sathishavm** [comment]
it would be more like `region:us-east-1a`

**Comment by masci** [comment]
Updated the README as per @sathishavm suggestion, closing.
