### ISSUE TITLE
Public client methods do not work with nil client

### ISSUE THREAD

**Issue by ods94065** [DataDog/datadog-go#51]
I can see that public `statsd.Client` methods are generally designed to be no-ops if the Client is nil. This has been a convenient way for us to disable Datadog e.g. for testing.

When coming back to this library after a while to double-check that this is indeed consistent and intended behavior, I noticed a test, `TestNilSafe`, that confirmed that this is intentional. However, I also discovered that there are several public methods, overlooked by `TestNilSafe`, that do _not_ work if the client is `nil`:

- `SetWriteTimeout`
- `Flush`
- `ServiceCheck`
- `SimpleServiceCheck`

I figure that, for completeness, all of these should be fixed up – particularly the service checks...

**Comment by masci** [comment]
Fixed on `master` by #52
