### ISSUE TITLE
How to use Distributions?

### ISSUE THREAD

**Issue by tjamet** [DataDog/datadog-go#58]
Hi,

I am trying to use the [distributions metric](https://godoc.org/github.com/DataDog/datadog-go/statsd#Client.Distribution) type, but this seems not to be documented in the DD statsD documentation https://docs.datadoghq.com/developers/dogstatsd/

I have tried, reading the [code](https://github.com/DataDog/datadog-go/blob/e67964b4021ad3a334e748e8811eb3cd6becbc6e/statsd/statsd_test.go#L38), to send the request directly to the DD statsD daemon but they do not appear in my DD dashboard.

Could you help me getting the feature to work?

Thank you

**Comment by aseemk** [comment]
My company is also very interested in this. We've found this documentation that mentions this is a beta feature for which you need to contact support FYI:

https://docs.datadoghq.com/graphing/metrics/distributions/

https://docs.datadoghq.com/developers/dogstatsd/data_types/#distributions

But we too would be interested in any more documentation. =) Thanks!

**Comment by arbll** [comment]
Hey there,

For anyone landing here, the docs have been updated quite a bit since this issue was opened. 
If you still have questions around distributions feel free to reach out to support@datadoghq.com.

Arthur
