### ISSUE TITLE
Make "statsdWriter" public

### ISSUE THREAD

**Issue by client9** [DataDog/datadog-go#64]
Hello,

The API has a public function

```
func NewWithWriter(w statsdWriter) (*Client, error) {
	client := &Client{writer: w, SkipErrors: false}
	return client, nil
}
```

but `statsdWriter` is a private type, so only the package and tests can use this function.    So, either make `NewWithWriter` private (rename to `newWithWriter`), or expose `statsdWriter`. 

```
type statsdWriter interface {
	Write(data []byte) (n int, err error)
	SetWriteTimeout(time.Duration) error
	Close() error
}
```

With the later, one would then write TCP writers, and even direct to datadog via HTTP API writers.

happy to whip up a PR as well, but I wanted to get thoughts before doing that.

regards,

n

**Comment by client9** [comment]
I think I'm in error.  You can pass in a object that satisfies a private interface, but it's really odd.

**Comment by arbll** [comment]
Agreed it's a bit odd. If anyone has a use case that depends on this feel free to open a PR. 
I'll close since this issue is pretty old and seems to be solved.
