### ISSUE TITLE
document what "rate" should be in the readme

### ISSUE THREAD

**Issue by grosser** [DataDog/datadog-go#70]
"rate argument should normally be 1 or less than that, e.g. 0.1 if you want to only send every 10th call"
maybe even better call the argument `sampleRate`

**Comment by arbll** [comment]
Hey @grosser,

Thanks for the suggestion. I agree this parameter can be confusing when using this library for the first time. #87 should improve that.

Arthur

**Comment by arbll** [comment]
Should be good after #87
