### ISSUE TITLE
documentation for Count is unclear

### ISSUE THREAD

**Issue by seebs** [DataDog/datadog-go#71]
```
func (c *Client) Count(name string, value int64, tags []string, rate float64) error

Count tracks how many times something happened per second. 
```

The relationship between `value` and `rate` is unspecified. Are they both used? How do they interact? If I'm just counting an event, usually I'm counting "total occurrences", not "times per second", because I'll compute times per second later.

Reading elsewhere suggests that "rate" should be a 0-1 value to control how often to actually send packets, so, a rate of "0.5" would indicate that 50% of packets should actually be sent, but I can't find anything in the datadog-go/statsd documentation that makes this explicit.

**Comment by arbll** [comment]
Hi @seebs, thanks for opening this issue

> Reading elsewhere suggests that "rate" should be a 0-1 value to control how often to actually send packets, so, a rate of "0.5" would indicate that 50% of packets should actually be sent, but I can't find anything in the datadog-go/statsd documentation that makes this explicit.

This is correct, you will only send 50% of the packets. Going to add some docs surrounding this in https://github.com/DataDog/datadog-go/pull/87. 
About the relationship between `value` and `rate` it works as the following:
- When a metric is sent with a specific sample rate we forward this information to the dogstatsd server: https://github.com/DataDog/datadog-go/blob/8a13fa761f51039f900738876f2837198fba804f/statsd/statsd.go#L210-L211
- When this metric is received by the dogstatsd server (probably the datadog-agent in our case) we try to take the sample rate into account: https://github.com/DataDog/datadog-agent/blob/33db6c888082da73e04a7d344b9c78ee3a72371d/pkg/metrics/counter.go#L26
That way you should get almost the same value even if you sample. 

I'll also add an entry in the readme about that. If anything is still unclear feel free to ask

**Comment by arbll** [comment]
Closing this one, feel free to open another issue if you still have questions.
