### ISSUE TITLE
DataDog build in master is broken

### ISSUE THREAD

**Issue by signalsensefred** [DataDog/datadog-go#9]
go get github.com/DataDog/datadog-go/statsd produces the following error:

murmur/signalsd/src/github.com/DataDog/datadog-go/statsd/statsd.go:358: e.text undefined (type Event has no field or method text, but does have Text)

**Comment by darron** [comment]
Here's the fix - just waiting for it to get merged:

https://github.com/DataDog/datadog-go/pull/10

**Comment by jmoiron** [comment]
Fixed in #10, thanks!
