### ISSUE TITLE
Missing WithAsyncUDS option?

### ISSUE THREAD

**Issue by rafaeljusto** [DataDog/datadog-go#97]
Hi, in the README.md the asynchronous mode is recommended, but I couldn't find the `WithAsyncUDS` option mentioned. Is it missing from the code?

From https://github.com/DataDog/datadog-go#blocking-vs-asynchronous-behavior:
> Currently, in 2.x, "blocking" is the default behavior to ensure backward compatibility. To use the "asynchronous" behavior, use the statsd.WithAsyncUDS() option. We recommend enabling the "asynchronous" mode.

If there're no plans to implement this option, it is safe to run a call in a goroutine if I don't care about the error?
```go
go statsd.Incr(...)
``` 

Thanks!

**Comment by arbll** [comment]
Hi @rafaeljusto,

The README was slightly outdated since https://github.com/DataDog/datadog-go/pull/91 got merged a few days ago. This option was dropped as it is now the default in v3.0.0. 
The README should now be up to date with those changes. Sorry for the confusion!

**Comment by rafaeljusto** [comment]
Thanks!
